<script src="{{ asset('client/js/vendor/jquery.js') }}"></script>
<script src="{{ asset('client/js/vendor/modernizer.min.js') }}"></script>
<script src="{{ asset('client/js/vendor/feather.min.js') }}"></script>
<script src="{{ asset('client/js/vendor/slick.min.js') }}"></script>
<script src="{{ asset('client/js/vendor/bootstrap.js') }}"></script>
<script src="{{ asset('client/js/vendor/text-type.js') }}"></script>
<script src="{{ asset('client/js/vendor/wow.js') }}"></script>
<script src="{{ asset('client/js/vendor/aos.js') }}"></script>
<script src="{{ asset('client/js/vendor/particles.js') }}"></script>
<!-- main JS -->
<script src="{{ asset('client/js/main.js') }}"></script>
